% [img] = display_bp_image(kernel_input_filename, image_filename)
%
% Displays and returns a complex image generated by SAR kernel 3
% (backprojection) from the TAV PERFECT benchmark suite.  The
% arguments are as follows:
%
%    kernel_input_filename : the input filename passed to the
%        kernel in order to generate the output in image_filename.
%        This is most likely kernel3_input.bin from the input
%        directory. This file is used only to set the image axes.
%
%    image_filename : filename of the output image to display.
%        This will typically be output_kernel3.bin from the working
%        directory corresponding to the kernel 3 execution.
%
% This function returns the complex image.
function [img] = display_bp_image(kernel_input_filename, image_filename)

    fp = fopen(kernel_input_filename, 'rb');
    fread(fp, 1, 'double');
    fread(fp, 1, 'double');
    dR = fread(fp, 1, 'double');
    fclose(fp);

    fp = fopen(image_filename, 'rb');
    img = fread(fp, inf, 'single');
    fclose(fp);

    img = complex(img(1:2:end),img(2:2:end));
    
    Nx = sqrt(numel(img));
    if Nx*Nx ~= numel(img), error('This script assumes square images.'); end
    Ny = Nx;

    img = reshape(img, [Nx Ny]);

    img = img.';
    xvals = (-(Nx/2)+0.5 + (0:Nx-1))*dR;
    yvals = (-(Ny/2)+0.5 + (0:Ny-1))*dR;

    figure; imagesc(yvals, xvals, 20*log10(abs(img./max(abs(img(:))))));
    axis xy;
    colorbar;
    caxis([-80 0]);
    xlabel('x (meters)');
    ylabel('y (meters)');
    title('Pixel magnitude in normalized decibel units')

end
